filebeat.inputs:
  # 첫 번째 로그 파일 그룹 (예: info 로그)
  - type: log
    enabled: true
    paths:
      - /var/logs/application/nestjs/app_*.log  # 서버의 info 로그
    tags: ["wellcheck-dev", "info-logs"]  # 서버 로그에 태그 추가

  # 두 번째 로그 파일 그룹 (예: error 로그)
  - type: log
    enabled: true
    paths:
      - /var/logs/application/nestjs/error_*.log  # 서버의 info 로그
    tags: ["wellcheck-dev", "error-logs"]  # 서버 로그에 태그 추가

output.logstash:
  hosts: ["host.docker.internal:5044"]  # Logstash 서버의 IP와 포트
